### ISSUE TITLE
Question about Ouster timestamp and GT pose timestamp

### ISSUE THREAD

**Issue by Taeyoung96** [TIERS/multi-lidar-dataset#8]
@Qingq-li   
Thanks for your great work!  
I think my question is similar to #7.  

In my case, I want to execute the SLAM algorithm with Ouster0_128.  
When I try to visualize my own trajectory with [evo](https://github.com/MichaelGrupp/evo), I found that Ouster's timestamp and GT timestamp is absolutely different.  

I used the `Indoor02(medium)` dataset.  
I checked the Ouster timestamp with `rostopic echo /os_cloud_node/points --noarr`, I got the result below.  
```
---
header: 
  seq: 6067
  stamp: 
    secs: 764
    nsecs:  38519990
  frame_id: "os_sensor"
height: 128
width: 2048
fields: "<array type: sensor_msgs/PointField, length: 9>"
is_bigendian: False
point_step: 48
row_step: 98304
data: "<array type: uint8, length: 12582912>"
is_dense: True
---
```  

And I check the GT pose timestamp with `rostopic echo /vrpn_client_node/UWBTest/pose`, I got the result below.    
```
---
header: 
  seq: 11362
  stamp: 
    secs: 1645463124
    nsecs: 389417356
  frame_id: "world"
pose: 
  position: 
    x: 0.995311319828
    y: 1.77796709538
    z: 1.33014786243
  orientation: 
    x: -0.528763532639
    y: 0.47708722949
    z: 0.639543950558
    w: -0.289448618889
---

```

The above results were captured at a similar time frame.  
But, Their timestamps are absolutely different.  

Is there anything I'm missing? I'd appreciate your help.  

Thanks,
